"""Build a :class:`MappingBook` from JSON instead of an Excel workbook.

Used when the mapping's source of truth lives outside Excel (e.g. the Next.js app
edits mapping data as JSON and points a suite's ``mapping:`` at a ``.json`` file).
The JSON shape is the direct dict-of-lists produced by ``etl-test export-mapping``
(dataclass field names, no Excel-style column aliasing needed):

    {
      "tables": [ {<TableMapping fields>, "columns": [ {<ColumnMapping fields>} ]} ],
      "business_rules": [ {<BusinessRule fields>} ],
      "ref_integrity":  [ {<RefIntegrityRule fields>} ],
      "warnings": [ ... ]            # ignored; regenerated by finalize()
    }

Unknown keys are ignored (forward-compatible), and key-marking/keyless warnings
are regenerated via ``MappingBook.finalize()`` so a JSON-loaded book is identical
to the Excel-loaded one it was exported from.
"""

from __future__ import annotations

import json
from dataclasses import fields
from pathlib import Path
from typing import Any

from ..exceptions import MappingError
from .models import (
    BusinessRule, ColumnMapping, MappingBook, RefIntegrityRule, TableMapping, _as_list,
)


def _only_known(cls: type, data: dict[str, Any]) -> dict[str, Any]:
    """Keep only keys that are actual dataclass fields of ``cls``."""
    names = {f.name for f in fields(cls)}
    return {k: v for k, v in data.items() if k in names}


def mapping_book_from_dict(data: dict[str, Any], source_file: str) -> MappingBook:
    if not isinstance(data, dict):
        raise MappingError("Mapping JSON must be an object with 'tables' etc.")
    book = MappingBook(source_file=source_file)

    for t in data.get("tables") or []:
        cols = t.get("columns") or []
        kwargs = _only_known(TableMapping, {k: v for k, v in t.items() if k != "columns"})
        if not kwargs.get("target_table"):
            continue
        kwargs["key_columns"] = _as_list(kwargs.get("key_columns"))
        if not isinstance(kwargs.get("options"), dict):
            kwargs["options"] = {}
        tm = TableMapping(**kwargs)
        tm.columns = [ColumnMapping(**_only_known(ColumnMapping, c)) for c in cols
                      if c.get("target_column")]
        book.tables[tm.target_table] = tm

    for r in data.get("business_rules") or []:
        kwargs = _only_known(BusinessRule, r)
        if not kwargs.get("rule_id") or not kwargs.get("target_table") or not kwargs.get("rule_type"):
            continue
        if not isinstance(kwargs.get("params"), dict):
            kwargs["params"] = {}
        book.business_rules.append(BusinessRule(**kwargs))

    for r in data.get("ref_integrity") or []:
        kwargs = _only_known(RefIntegrityRule, r)
        kwargs["child_columns"] = _as_list(kwargs.get("child_columns"))
        kwargs["parent_columns"] = _as_list(kwargs.get("parent_columns"))
        if not kwargs.get("child_table") or not kwargs.get("parent_table"):
            continue
        if not kwargs["child_columns"] or not kwargs["parent_columns"]:
            continue
        book.ref_integrity.append(RefIntegrityRule(**kwargs))

    return book.finalize()


def parse_mapping_json(path: str | Path) -> MappingBook:
    p = Path(path)
    if not p.exists():
        raise MappingError(f"Mapping JSON not found: {p}")
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise MappingError(f"Invalid mapping JSON {p}: {exc}") from exc
    return mapping_book_from_dict(data, str(p))
